language: go
sudo: false
go:
  - tip
before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/awalterschulze/gographviz
  - yum install -y graphviz
script:
  - go test -v
  - $GOPATH/bin/goveralls -service=travis-ci